sub: #è¿œç¨‹Clashé…ç½®æ–‡ä»¶ï¼Œæ³¨æœ‰#çš„æ˜¯å¤±æ•ˆçš„é“¾æ¥
# proxypoolèŠ‚ç‚¹æ± 
 # å°ç«ç®­
  - https://www.xrayvip.com/free.yaml #åŒä¸Šï¼Œhttps://t.me/xrayfree ç›®å‰ä¸»åŠ›clashè®¢é˜…é“¾æ¥
 # httpså¼€å¤´
  - https://api.v1.mk/sub?target=clash&url=https://raw.githubusercontent.com/Jsnzkpg/Jsnzkpg/Jsnzkpg/Jsnzkpg #æ¯å¤©æ›´æ–°ï¼Œæ³¨æ„çœ‹æŠ“å–é€Ÿåº¦
 # GitHubæ‰˜ç®¡clashè®¢é˜…é“¾æ¥
  - https://api.v1.mk/sub?target=clash&url=https://raw.githubusercontent.com/aiboboxx/clashfree/main/clash.yml #clashå…¬ç›Šå…è´¹èŠ‚ç‚¹è®¢é˜…æ¯å¤©æ›´æ–°
 # GitHubæ‰˜ç®¡b64è®¢é˜…é“¾æ¥
# - https://api.v1.mk/sub?target=clash&url=https://raw.githubusercontent.com/freefq/free/master/v2 #freev2ï¼Œä¸æ€ä¹ˆæ›´æ–°äº†ï¼Œæœ€æ–°æ˜¯2æœˆä»½çš„ï¼ŒåæœŸå¯å…³æ³¨ğŸš©
  - https://api.v1.mk/sub?target=clash&url=https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2 #v2rayfreeï¼Œè¿™ä¸ªå¯ä»¥æ¨èæœ‹å‹å…è´¹ç”¨
 # GitLabæ‰˜ç®¡b64è®¢é˜…é“¾æ¥
 # è®¢é˜…è½¬æ¢æ¨¡ç‰ˆ
# - https://api.v1.mk/sub?target=clash&url=http://weoknow.com/data/dayupdate/1/z.yaml
# - https://raw.githubusercontent.com/anjue39/PoolActions/main/subscribe/clash.yaml
  - https://api.v1.mk/sub?target=clash&url=http://weoknow.com/data/dayupdate/1/z1.txt&insert=false&list=true
  #- https://api.v1.mk/sub?target=clash&url=http://weoknow.com/data/dayupdate/2/z1.txt&insert=false&list=true
# - http://weoknow.com/data/dayupdate/1/z.yaml
# - http://weoknow.com/data/dayupdate/2/z.yaml
  #- https://raw.githubusercontent.com/mfuu/v2ray/master/clash.yaml #ä¸é”™çš„å…è´¹ç«™ç‚¹ï¼Œæ¯å¤©æ›´æ–°ï¼Œé‡Œé¢æœ‰å¤§é‡åˆå¹¶çš„èŠ‚ç‚¹ï¼Œæœ‰listæº
# now
  #- https://api.v1.mk/sub?target=clash&url=https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub #ğŸ±
  #- https://raw.githubusercontent.com/vxiaov/free_proxies/main/clash/clash.provider.yaml #ğŸ±æœ‰ä¸€ä¸ªæœˆæ²¡æ›´æ–°äº†ï¼Œæ²¡äº‹çœ‹ä¸€ä¸‹
#- https://raw.githubusercontent.com/ronghuaxueleng/get_v2/main/pub/changfengoss.yaml #ğŸš©é•¿é£çš„
#- https://raw.githubusercontent.com/ronghuaxueleng/get_v2/main/pub/combine.yaml #ğŸš©
 # - https://api.v1.mk/sub?target=clash&url=https://jiang.netlify.app&insert=false&list=true #ğŸš©äºŒçˆ·ç¿»å¢™
  # 23.9.16 add
  - http://150.230.195.209:12580/clash/proxies
  # 24.5.16 add
  - https://api.v1.mk/sub?target=clash&url=https://raw.githubusercontent.com/MrMohebi/xray-proxy-grabber-telegram/master/collected-proxies/clash-meta/actives_under_1000ms.yaml
  # 24.10.23 add
  - https://api.v1.mk/sub?target=clash&url=https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta.yaml
  - https://api.v1.mk/sub?target=clash&url=https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta-2.yaml
  # 25.1.2 add
  - http://141.147.161.50:12580/clash/proxies
  - http://150.230.195.209:12580/clash/proxies
  - http://155.248.172.106:12580/clash/proxies
  - http://66.42.50.118:12580/clash/proxies
  - http://140.238.31.152:12580/clash/proxies
  - https://proxypool.link/clash/proxies
  - https://api.v1.mk/sub?target=clash&url=https://proxypool1999.banyunxiaoxi.icu/clash/proxies&insert=false&list=true
  # 25.1.10 add
  - https://api.v1.mk/sub?target=clash&url=https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/speednodes.yaml&insert=false&list=true
  # 25.3.26 add
  - https://api.v1.mk/sub?target=clash&url=https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.meta.yml&insert=false&list=true
  - https://api.v1.mk/sub?target=clash&url=https://raw.githubusercontent.com/peasoft/NoMoreWalls/refs/heads/master/list.meta.yml&insert=false&list=true
  - https://api.v1.mk/sub?target=clash&url=https://raw.githubusercontent.com/Flikify/Free-Node/refs/heads/main/clash.yaml
  - https://api.v1.mk/sub?target=clash&url=https://raw.githubusercontent.com/xiaoji235/airport-free/main/clash/naidounode.txt
  - https://api.v1.mk/sub?target=clash&url=https://fastly.jsdelivr.net/gh/dongchengjie/airport@main/subs/merged/tested_within.yaml
  # 25.4.1 add
  - https://proxypool.link/clash/proxies
# openit
# - https://raw.githubusercontent.com/yu-steven/openit/main/Clash.yaml #å›ç¯è®¢é˜…
# - https://raw.githubusercontent.com/yu-steven/openit/main/utils/pool/pool.yaml #å…¥åº“è®¢é˜…
# openit
# - https://raw.githubusercontent.com/anjue39/openit/main/Clash.yaml #å›ç¯è®¢é˜…
# - https://raw.githubusercontent.com/anjue39/openit/main/utils/pool/pool.yaml #å…¥åº“è®¢é˜…
# TopPreeProxy
# - https://raw.githubusercontent.com/alanbobs999/TopFreeProxies/master/sub/sub_merge_clash.yaml
local: ["into.yaml","../../Clash.yaml"] #åŒçº§ã€ä¸Šçº§æˆ–ä¸‹çº§ç›®å½•çš„æœ¬åœ°Clashé…ç½®æ–‡ä»¶ï¼Œä¸Šçº§ç›®å½•çš„æ–‡ä»¶éœ€è¦ä½¿ç”¨"../"è¿›è¡Œå¼•å¯¼
