sub: #è¿œç¨‹Clashé…ç½®æ–‡ä»¶ï¼Œæ³¨æœ‰#çš„æ˜¯å¤±æ•ˆçš„é“¾æ¥
# proxypoolèŠ‚ç‚¹æ± 
  - https://www.xrayvip.com/free.yaml #åŒä¸Šï¼Œhttps://t.me/xrayfree ç›®å‰ä¸»åŠ›clashè®¢é˜…é“¾æ¥
  - https://api-suc.0z.gs/sub?target=clash&url=http://weoknow.com/data/dayupdate/1/z1.txt&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=http://weoknow.com/data/dayupdate/2/z1.txt&insert=false&list=true
# - http://weoknow.com/data/dayupdate/1/z.yaml
# - http://weoknow.com/data/dayupdate/2/z.yaml
# - https://api-suc.0z.gs/sub?target=clash&url=http://weoknow.com/data/dayupdate/1/z.yaml
  - https://api-suc.0z.gs/sub?target=clash&url=https://jiang.netlify.app&insert=false&list=true #ğŸš©äºŒçˆ·ç¿»å¢™
  - http://150.230.195.209:12580/clash/proxies
 #- https://proxypool.link/clash/proxies
# GitHubæ‰˜ç®¡clashè®¢é˜…é“¾æ¥
# - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/aiboboxx/clashfree/main/clash.yml&insert=false&list=true #ğŸ±clashå…¬ç›Šå…è´¹èŠ‚ç‚¹è®¢é˜…æ¯å¤©æ›´æ–°ï¼Œ12æœˆä»¥åæ”¹æˆåŠ¨æ€çš„æ—¥æœŸäº†
# - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2&insert=false&list=true #ğŸ±v2rayfreeï¼Œè¿™ä¸ªå¯ä»¥æ¨èæœ‹å‹å…è´¹ç”¨ğŸš©
  - https://raw.githubusercontent.com/Jsnzkpg/Jsnzkpg/Jsnzkpg/Jsnzkpg #æ¯å¤©æ›´æ–°ï¼Œæ³¨æ„çœ‹æŠ“å–é€Ÿåº¦
  - https://raw.githubusercontent.com/mfuu/v2ray/master/clash.yaml #ä¸é”™çš„å…è´¹ç«™ç‚¹ï¼Œæ¯å¤©æ›´æ–°ï¼Œé‡Œé¢æœ‰å¤§é‡åˆå¹¶çš„èŠ‚ç‚¹ï¼Œæœ‰listæº
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub&insert=false&list=true #ğŸ±12æœˆåæ”¹æˆåŠ¨æ€çš„äº†
# - https://raw.githubusercontent.com/anjue39/PoolActions/main/subscribe/clash.yaml
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/MrMohebi/xray-proxy-grabber-telegram/master/collected-proxies/clash-meta/actives_under_1000ms.yaml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/MrMohebi/xray-proxy-grabber-telegram/master/collected-proxies/clash-meta/all.yaml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta.yaml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta-2.yaml&insert=false&list=true
# 25.1.2 add
  - http://66.42.50.118:12580/clash/proxies
  - http://140.238.31.152:12580/clash/proxies
  - https://proxypool1999.banyunxiaoxi.icu/clash/proxies
# 25.3.26 add
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.meta.yml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/peasoft/NoMoreWalls/refs/heads/master/list.meta.yml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/Flikify/Free-Node/main/clash.yaml
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/xiaoji235/airport-free/main/clash/naidounode.txt
  - https://api-suc.0z.gs/sub?target=clash&url=https://fastly.jsdelivr.net/gh/dongchengjie/airport@main/subs/merged/tested_within.yaml
# 25.4.1 add
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/linzjian666/chromego_extractor/main/outputs/clash_meta_warp.yaml&insert=false&list=true
 #- https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/Eternity.yml&insert=false&list=true #æµ‹é€Ÿåç¾å›½æœåŠ¡å™¨ä¼˜é€‰é«˜é€ŸèŠ‚ç‚¹200ä¸ª
 # - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge_yaml.yml&insert=false&list=true #éæµ‹é€Ÿåçš„æ‰€æœ‰èŠ‚ç‚¹ï¼Œä¾¿äºæœ¬åœ°æµ‹è¯•
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml&insert=false&list=true
# 25.9.4 add
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/ndnode.yaml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/yudou66.yaml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/wenode.yaml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/nodefree.yaml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/nodev2ray.yaml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/clashmeta.yaml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/v2rayshare.yaml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/ermaozi01/free_clash_vpn/main/subscribe/clash.yml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/speednodes.yaml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/itxve/fetch-clash-node/main/node/ClashNode.yaml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/ermaozi01/free_clash_vpn/main/subscribe/clash.yml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/speednodes.yaml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/itxve/fetch-clash-node/main/node/ClashNode.yaml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/Flik6/getNode/main/clash.yaml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/free18/v2ray/main/c.yaml&insert=false&list=true
  - https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/ts-sf/fly/main/clash&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/baip01/clash/main/clash&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/ssrsub/ssr/master/clash.yaml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/chongdong1230/dxz/main/clash&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/AzadNetCH/Clash/main/AzadNet.txt&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/go4sharing/sub/main/sub.yaml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/moneyfly1/collectSub/main/output/all.txt&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/lagzian/SS-Collector/main/mix_clash.yaml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/ALIILAPRO/v2rayNG-Config/main/sub.txt&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/NiREvil/vless/main/sub/clash-meta-wg.yml&insert=false&list=true
  - https://api-suc.0z.gs/sub?target=clash&url=https://raw.githubusercontent.com/Misaka-blog/chromego_merge/main/sub/merged_proxies_new.yaml&insert=false&list=true
# - https://s.jhb.edu.kg/sub?target=clash&url=https%3A%2F%2Fopenit.anjue39.qzz.io%2F97e79a62-f686-4b91-87a7-be39c9e57658%2Fsub&insert=false
# openit
# - https://raw.githubusercontent.com/yu-steven/openit/main/Clash.yaml #å›ç¯è®¢é˜…
# - https://raw.githubusercontent.com/yu-steven/openit/main/utils/pool/pool.yaml #å…¥åº“è®¢é˜…
# openit
# - https://raw.githubusercontent.com/anjue39/openit/main/Clash.yaml #å›ç¯è®¢é˜…
# - https://raw.githubusercontent.com/anjue39/openit/main/utils/pool/pool.yaml #å…¥åº“è®¢é˜…
# TopPreeProxy
# - https://raw.githubusercontent.com/alanbobs999/TopFreeProxies/master/sub/sub_merge_clash.yaml
local: ["into.yaml","../../Clash.yaml"] #åŒçº§ã€ä¸Šçº§æˆ–ä¸‹çº§ç›®å½•çš„æœ¬åœ°Clashé…ç½®æ–‡ä»¶ï¼Œä¸Šçº§ç›®å½•çš„æ–‡ä»¶éœ€è¦ä½¿ç”¨"../"è¿›è¡Œå¼•å¯¼
