name: Nodes_pages

on: 
  workflow_dispatch:

jobs: 
  my-job: 
    name: Max Job
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '21.x'
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git config
      run: |
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    - name: npm
      run: cd ./utils/rm/ && npm ci
    - name: Download source
      run: curl -L "https://page.anjue39.qzz.io/ok/sub?target=clash" -o ./utils/subconverter/check.yaml
    - name: subconverter
      run: |
         cd ./utils/subconverter/
         ./subconverter -g --artifact "clash"
         ./subconverter -g --artifact "long"
         ./subconverter -g --artifact "output"
         ./subconverter -g --artifact "clash2base64"
    - name: marge urls
      run: |
         base64 -d ./utils/subconverter/check > ./utils/rm/url1
         cat ./utils/rm/url1 ./sub/url2 > ./utils/rm/url
         rm ./utils/subconverter/check ./utils/rm/url1
    - name: remove & rename
      run: cd ./utils/rm/ && npm start
    - name: url & https
      run: |
         rm ./utils/rm/url
         mv ./utils/rm/out ./url
         ./.github/url.sh > ./1
         cp url 2
         cat 1 2 > 3 && rm 1 2
         base64 3 > https -w 0 && rm 3
         base64 ./url > ./utils/subconverter/base64 -w 0
    - name: long & Clash.yaml
      run: |
         mv ./utils/subconverter/Clash.yaml ./Clash.yaml || true
         mv ./utils/subconverter/long ./long || true
         mv ./utils/subconverter/output.txt ./utils/pool/output.txt || true
         rm ./utils/subconverter/base64 ./utils/subconverter/output.yaml || true
    - name: git push
      run: ./.github/update-repo.sh || true
